### ISSUE TITLE
INVALID_PARAMETERS error on request

### ISSUE THREAD

**Issue by whats0n0** [Wopify/node-bankid#2]
![fjbcbf3](https://cloud.githubusercontent.com/assets/4086334/16994133/5c3544e8-4ea6-11e6-9956-7087e7a98d04.png)

I think this is caused by the method (in this case, "Auth") not being included in the request. The spec doesn't specify how the method is supposed to be included.

**Comment by tskarhed** [comment]
Most likely caused by faulty `personalNumber`
https://github.com/Wopify/node-bankid/blob/master/example.js#L5

https://www.bankid.com/assets/bankid/rp/bankid-relying-party-guidelines-v2.10.pdf
**_12.8.5 Error Codes Collect**_
INVALID_PARAMETERS

```
RP must not try the same request again. This
is an internal error within RP's system and
must not be communicated to the user as a
BankID-error.
```

**Comment by whats0n0** [comment]
Nope, I have tried with my own in the correct format.

**12.4 PersonalNumberType**
Example with personal number (“personnummer”)

```
<!-- ID number-->
<!-- 12 digits. Century must be included -->
<personalNumber>198103091234</personalNumber>
```

**Comment by whats0n0** [comment]
See #3.
